# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sample-web-app-cars

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v3
      #      - name: Set up JDK 15
      #        uses: actions/setup-java@v3
      #        with:
      #          java-version: '8'
      #          distribution: 'adopt'

      - name: Remove target
        run: rm -r ./target
      - name: Build with Maven
        run: mvn clean install
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.AzureAppService_ContainerUsername_47cc0a33dbbf4576a2e47ba86543f42b }}
          password: ${{ secrets.AzureAppService_ContainerPassword_7d1e37f53f714c599f97cb2134ed480f }}

          #      - name: Build the Docker image
          #        run: docker build --load -t sample-web-app-cars.jar:latest -t sample-web-app-cars.jar:$(date +%s) --target deploy .
          #
          #      - name: Docker Push
          #        run: |
          #          docker push sample-web-app-cars.jar:latest
          #          docker push sample-web-app-cars.jar:$(date +%s)

          - name: Build and push container image to registry
            if: github.event_name == 'push'
            uses: docker/build-push-action@v2
            with:
              context: .
              push: true
              tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_47cc0a33dbbf4576a2e47ba86543f42b }}/sample-web-app-cars.jar:latest

            # Push the new release
          - name: Build and Push New Release
            if: github.event_name == 'release'
            uses: docker/build-push-action@v2
            with:
              context: .
              push: true
              tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_47cc0a33dbbf4576a2e47ba86543f42b }}/sample-web-app-cars.jar:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'sample-web-app-cars'
          slot-name: 'production'
          publish-profile: ${{ secrets.AzureAppService_PublishProfile_1708485bd0f548d7904c1650754b9ef7 }}
          images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_47cc0a33dbbf4576a2e47ba86543f42b }}/sample-web-app-cars.jar:${{ github.sha }}'
